//
// Generated by JTB 1.3.2
//

package minijava.visitor;
import minijava.syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> &lt;EOF&gt;
    * </PRE>
    */
   public void visit(Goal n, A argu);

   /**
    * <PRE>
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> ( VarDeclaration() )*
    * f15 -> ( Statement() )*
    * f16 -> "}"
    * f17 -> "}"
    * </PRE>
    */
   public void visit(MainClass n, A argu);

   /**
    * <PRE>
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    * </PRE>
    */
   public void visit(TypeDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    * </PRE>
    */
   public void visit(ClassDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    * </PRE>
    */
   public void visit(ClassExtendsDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    * </PRE>
    */
   public void visit(VarDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    * </PRE>
    */
   public void visit(MethodDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    * </PRE>
    */
   public void visit(FormalParameterList n, A argu);

   /**
    * <PRE>
    * f0 -> Type()
    * f1 -> Identifier()
    * </PRE>
    */
   public void visit(FormalParameter n, A argu);

   /**
    * <PRE>
    * f0 -> ","
    * f1 -> FormalParameter()
    * </PRE>
    */
   public void visit(FormalParameterRest n, A argu);

   /**
    * <PRE>
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    * </PRE>
    */
   public void visit(Type n, A argu);

   /**
    * <PRE>
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    * </PRE>
    */
   public void visit(ArrayType n, A argu);

   /**
    * <PRE>
    * f0 -> "boolean"
    * </PRE>
    */
   public void visit(BooleanType n, A argu);

   /**
    * <PRE>
    * f0 -> "int"
    * </PRE>
    */
   public void visit(IntegerType n, A argu);

   /**
    * <PRE>
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    * </PRE>
    */
   public void visit(Statement n, A argu);

   /**
    * <PRE>
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    * </PRE>
    */
   public void visit(Block n, A argu);

   /**
    * <PRE>
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    * </PRE>
    */
   public void visit(AssignmentStatement n, A argu);

   /**
    * <PRE>
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    * </PRE>
    */
   public void visit(ArrayAssignmentStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    * </PRE>
    */
   public void visit(IfStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * </PRE>
    */
   public void visit(WhileStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    * </PRE>
    */
   public void visit(PrintStatement n, A argu);

   /**
    * <PRE>
    * f0 -> AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    * </PRE>
    */
   public void visit(Expression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(AndExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "&lt;"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(CompareExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(PlusExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(MinusExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(TimesExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    * </PRE>
    */
   public void visit(ArrayLookup n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    * </PRE>
    */
   public void visit(ArrayLength n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    * </PRE>
    */
   public void visit(MessageSend n, A argu);

   /**
    * <PRE>
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    * </PRE>
    */
   public void visit(ExpressionList n, A argu);

   /**
    * <PRE>
    * f0 -> ","
    * f1 -> Expression()
    * </PRE>
    */
   public void visit(ExpressionRest n, A argu);

   /**
    * <PRE>
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    * </PRE>
    */
   public void visit(PrimaryExpression n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public void visit(IntegerLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> "true"
    * </PRE>
    */
   public void visit(TrueLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> "false"
    * </PRE>
    */
   public void visit(FalseLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(Identifier n, A argu);

   /**
    * <PRE>
    * f0 -> "this"
    * </PRE>
    */
   public void visit(ThisExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    * </PRE>
    */
   public void visit(ArrayAllocationExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    * </PRE>
    */
   public void visit(AllocationExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "!"
    * f1 -> Expression()
    * </PRE>
    */
   public void visit(NotExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    * </PRE>
    */
   public void visit(BracketExpression n, A argu);

}

